import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar.jsx/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-1">

        <div><Navbar></Navbar></div>
        <div>
        {children}
        </div>
        
        </body>
    </html>
  );
}
